// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuW1ugsdCKY597-XvYhZgyAWjnjKLowsc',
    appId: '1:288062969366:web:1b47c8b19be8a2fa820737',
    messagingSenderId: '288062969366',
    projectId: 'video-generator-app-dc8ee',
    authDomain: 'video-generator-app-dc8ee.firebaseapp.com',
    storageBucket: 'video-generator-app-dc8ee.firebasestorage.app',
    measurementId: 'G-4FCK58P396',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCbO9rbgPV8jQ2MV1_NUiq3mP-fLVZ95M',
    appId: '1:288062969366:android:4f569b0b48bbaed5820737',
    messagingSenderId: '288062969366',
    projectId: 'video-generator-app-dc8ee',
    storageBucket: 'video-generator-app-dc8ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5r5w8miwwZpvQ5JOonCNbMUtpRe-Z5Tw',
    appId: '1:288062969366:ios:0515db59b82c8bff820737',
    messagingSenderId: '288062969366',
    projectId: 'video-generator-app-dc8ee',
    storageBucket: 'video-generator-app-dc8ee.firebasestorage.app',
    iosBundleId: 'com.example.videoGenApp',
  );
}
